services:
  website:
    container_name: qurt-website
    image: nurtai325/qurt-website:latest
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./landing:/usr/share/nginx/html
      - ./assets:/usr/share/nginx/html/assets
      - ./editor:/usr/share/nginx/html/editor
      - ./nginx/99-autoreload.sh:/docker-entrypoint.d/99-autoreload.sh
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 60
  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 24h & wait $${!}; done;'"
